### ISSUE TITLE
Allow option to write generated hosts file to stdout (or a file)

### ISSUE THREAD

**Issue by alanorth** [tbds/FreeContributor#1]
I use unbound on Mac OS X and would rather use `include` in the config to point to my blocking data, ie:

```
include: /path/to/unbound/local-blocking-data.conf
```

It would be nice if your script could output the generated blocking data to stdout or a file.

**Comment by tbds** [comment]
Right now I am working only with dnsmasq.

By default if you select unbound the file goes to /etc/unbound/unbound-block.conf 

But you cand find an [unbound config template](https://github.com/tbds/FreeContributor/blob/master/conf/unbound.conf)

#
# ~/etc/unbound/unbound.conf
#

#Use this to include other text into the file.
include: /etc/unbound/unbound-block.conf

**Comment by alanorth** [comment]
Yes, I'm using unbound and I'm already including [another hosts file to block ad and malware domains](https://github.com/jodrell/unbound-block-hosts). I just meant that your script should be able to output a file in addition to requiring root and modifying files in the file system. :)

**Comment by tbds** [comment]
I will rewrite the code but take a look of this script

https://github.com/moviuro/net-tools/blob/master/lie-to-me
