### ISSUE TITLE
./FreeContributor.sh -f unbound -o unboundblock.conf -t NXDOMAIN    gives me syntax error

### ISSUE THREAD

**Issue by ateepy** [tbds/FreeContributor#10]
./FreeContributor.sh -f unbound -o unboundblock.conf -t NXDOMAIN

	 Domains extracted using unbound format: 81318
 * Starting recursive DNS server unbound                                                            /etc/unbound/unboundblock.conf:1: error: syntax error
read /etc/unbound/unboundblock.conf failed: 1 errors in configuration file
[1466915406] unbound[4791:0] fatal error: Could not read config file: /etc/unbound/unbound.conf
                                                                                             [fail]
    FreeContributor successfully installed
    Enjoy surfing in the web
    More info at https://tbds.github.io/FreeContributor/

root@ubuntu-512mb-nyc3-01:~/FreeContributor# rm /etc/unbound/unboundblock.conf
root@ubuntu-512mb-nyc3-01:~/FreeContributor# mv unboundblock.conf /etc/unbound/
root@ubuntu-512mb-nyc3-01:/etc/unbound# service unbound stop
 * Stopping recursive DNS server unbound                                                     [ OK ] 
root@ubuntu-512mb-nyc3-01:/etc/unbound# unbound-checkconf
/etc/unbound/unboundblock.conf:1: error: syntax error
read /etc/unbound/unboundblock.conf failed: 1 errors in configuration file

First couple entries of unboundblock.conf:
local-zone: "000007.ru" static
local-zone: "0000mps.webpreview.dsl.net" static
local-zone: "0001.2waky.com" static

Whole unbound.conf:
http://pastebin.com/s3NAhV6M

**Comment by tbds** [comment]
My suggestion: remove all files unbound related and start over.

Use as a template the unbound.conf provided [here][https://github.com/tbds/FreeContributor/blob/master/conf/unbound.conf]

**Comment by ateepy** [comment]
KK

**Comment by tbds** [comment]
Hi again. Before start Unbound you need to run the following command 

> unbound-control-setup

which will generate a self-signed certificate and private key for the server, as well as the client. These files will be created in the /etc/unbound directory

After that, edit _/etc/unbound/unbound.conf_ and put the following contents in that. The control-enable: yes option is necessary, the rest can be adjusted as required.

>   remote-control:
>     # Enable remote control with unbound-control(8) here.
>     # set up the keys and certificates with unbound-control-setup.
>     control-enable: yes
>    
>     # what interfaces are listened to for remote control.
>     # give 0.0.0.0 and ::0 to listen to all interfaces.
>     control-interface: 127.0.0.1
>    
>     # port number for remote control operations.
>     control-port: 8953
>    
>     # unbound server key file.
>     server-key-file: "/etc/unbound/unbound_server.key"
>    
>     # unbound server certificate file.
>     server-cert-file: "/etc/unbound/unbound_server.pem"
>    
>     # unbound-control key file.
>     control-key-file: "/etc/unbound/unbound_control.key"
>    
>     # unbound-control certificate file.
>     control-cert-file: "/etc/unbound/unbound_control.pem"

Source: [Archwiki Unbound](https://wiki.archlinux.org/index.php/Unbound)

**Comment by ateepy** [comment]
using new debian server
unbound conf from freecontributor with nothing uncommented only spelling mistakes changed

still:

root@debian-512mb-nyc3-01:/etc/unbound# unbound-checkconf
/etc/unbound/unboundblock.conf:1: error: syntax error
read /etc/unbound/unboundblock.conf failed: 1 errors in configuration file
root@debian-512mb-nyc3-01:/etc/unbound#

**Comment by ateepy** [comment]
i found the issue for this problem. The include for the blocklist needs to be indented to match the syntax. lol

**Comment by ateepy** [comment]
new problem: 

root@debian-512mb-nyc3-01:/etc/unbound# unbound-checkconf
[1467617911] unbound-checkconf[5791:0] warning: duplicate local-zone
[1467617911] unbound-checkconf[5791:0] error: could not enter zone zimeks.com.mk static
[1467617911] unbound-checkconf[5791:0] fatal error: failed local-zone, local-data configuration

**Comment by ateepy** [comment]
another double: 
root@debian-512mb-nyc3-01:/etc/unbound# unbound-checkconf
[1467618727] unbound-checkconf[5800:0] warning: duplicate local-zone
[1467618727] unbound-checkconf[5800:0] error: could not enter zone zief.pl static
[1467618727] unbound-checkconf[5800:0] fatal error: failed local-zone, local-data configuration

**Comment by ateepy** [comment]
another one:
[1467618911] unbound-checkconf[5804:0] warning: duplicate local-zone
[1467618911] unbound-checkconf[5804:0] error: could not enter zone ziccardia.com static
[1467618911] unbound-checkconf[5804:0] fatal error: failed local-zone, local-data configuration

**Comment by ateepy** [comment]
went through a bunch of these dups and deleted them but it's never ending

**Comment by tbds** [comment]
Start over. Remove all the files you have and the FreeContributor repo and download again.

I tested with unbound and it works.

> unbound-checkconf: no errors in /etc/unbound/unbound.conf

**Comment by ateepy** [comment]
went through a bunch of these dups and deleted them but it's never ending

**Comment by tbds** [comment]
Well if you have difficulties with unbound, try dnsmasq, much simpler and does the same job.
