### ISSUE TITLE
spelling mistakes 

### ISSUE THREAD

**Issue by ateepy** [tbds/FreeContributor#11]
two spelling mistakes in: https://raw.githubusercontent.com/tbds/FreeContributor/master/conf/unbound.conf

        # unbound server key file.
	server-key-file: "/etc/unbound/unbound_server.key"

	# unbound server certificate file.
	server-cert-file: "/etc/unboundunbound_server.pem"  <<<here<<<<

	# unbound-control key file.
	control-key-file: "/etc/unbound/unbound_control.key"

	# unbound-control certificate file.
	control-cert-file: "/etc/unboundunbound_control.pem"  <<<here<<<<

**Comment by tbds** [comment]
Fixed.
