### ISSUE TITLE
unbound list wont work with smallest digital ocean ubuntu instance

### ISSUE THREAD

**Issue by ateepy** [tbds/FreeContributor#13]
the full block list wont work on the smallest DO ubuntu instance. Oddly enough, the 512mb ram Debian instance worked for a little bit then stopped for some reason, so I made a ubuntu 512mb ram instance and it flat out did work. When I resized the ubuntu instance to 2gig ram it worked.

Now im gonna resize the debian.

**Comment by tbds** [comment]
I change the default list to reduce the number of domains to block.

**Comment by ateepy** [comment]
thanks, also theres a buncha duplicates.
uniq old.txt > new.txt helped but i still had to manually delete a couple entries that were dups with capital letters.
