### ISSUE TITLE
dnmasq configuration changes

### ISSUE THREAD

**Issue by rorshack** [tbds/FreeContributor#14]
I dont look at the code but i already have dnsmasq running and after running the script /etc/dnsmasq.conf have changed. I have port=0. Using port=0 in dnsmasq.conf broke anything with the hostblocking business? Thank you

**Comment by tbds** [comment]
Yes. By default FreeContributor backups the previous dnsmaq.conf and change it by the one provided in the conf folder.

```

  if [ -f "${DNSMASQCONF}" ]; then
    cp "${DNSMASQCONF}" "${DNSMASQCONFBAK}"
  fi

cp "${DIR}"/conf/dnsmasq.conf "${DNSMASQCONF}"
```

Just replace it by the backup file

```
mv /etc/dnsmasq.conf.bak /etc/dnsmasq.conf

```

Restart the service and that's it.
