### ISSUE TITLE
disqus

### ISSUE THREAD

**Issue by condor0765** [tbds/FreeContributor#15]
Would it be a good idea to block disqus. In addition to
https://en.wikipedia.org/wiki/Disqus#Criticism_and_privacy_concerns
I always get annoyed by its big heavy page loading using javascript freezing the browser. Thanks for your great work.

**Comment by tbds** [comment]
Done. [Check last commit](https://github.com/tbds/FreeContributor/commit/65cfee8fda4279991c999cf95f39767cb4721e58).
