### ISSUE TITLE
FreeContributor.sh Fails with GNU Awk 4.0.2

### ISSUE THREAD

**Issue by Darkz** [tbds/FreeContributor#16]
Executing FreeContributor.sh -f dnsmasq -t NXDOMAIN fails.

`[root@compute3 FreeContributor]# sh FreeContributor.sh -f dnsmasq -t NXDOMAIN

```
 _____               ____            _        _ _           _             
|  ___| __ ___  ___ / ___|___  _ __ | |_ _ __(_) |__  _   _| |_ ___  _ __ 
| |_ | '__/ _ \/ _ \ |   / _ \| '_ \| __| '__| | '_ \| | | | __/ _ \| '__|
|  _|| | |  __/  __/ |__| (_) | | | | |_| |  | | |_) | |_| | || (_) | |   
|_|  |_|  \___|\___|\____\___/|_| |_|\__|_|  |_|_.__/ \__,_|\__\___/|_|   


Script to extract and convert domains lists from various sources.

FreeContributor - http://github.com/tbds/FreeContributor
Released under the GPLv3 license
(c) 2016 tbds, gcarq and contributors

Checking dependencies...

     - Checking if curl is installed...
     Status: Ok

     - Checking if dnsmasq is installed...
     Status: Ok

FreeContributor is downloading data...

Extracting domains from previous lists...
Usage: awk [POSIX or GNU style options] -f progfile [--] file ...
Usage: awk [POSIX or GNU style options] [--] 'program' file ...
.......
Followed by the awk help. ( as in awk -V )
```

Sadly I know nothing about sed or awk to try to pinpoint the offending domain, i will still try and comeback if y get anything usefull.

**Comment by tbds** [comment]
Comment line [331](https://github.com/tbds/FreeContributor/blob/master/FreeContributor.sh#L331)

Put some echos to see after which line the code breaks.

**Comment by fourways22** [comment]
Hello 
I've the same problem.

**Comment by receptor** [comment]
Same problem:
Extracting domains from previous lists...
awk: not an option: -i

**Comment by tbds** [comment]
@receptor @fourways22 I need more details: Operative system, (distro and version), and version of awk (works on 4.1.4)

**Comment by receptor** [comment]
@tbds I'm running it on a Raspberry Pi :)
```
pi@pibox:~ $ uname -a
Linux pibox 4.4.32+ #924 Tue Nov 15 18:06:42 GMT 2016 armv6l GNU/Linux

pi@pibox:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"

pi@pibox:~ $ awk -W version
mawk 1.3.3 Nov 1996, Copyright (C) Michael D. Brennan
compiled limits:
max NF             32767
sprintf buffer      1020
```

**Comment by tbds** [comment]
@receptor your are using mawk (an interpreter for the AWK programming language), not awk or gawk. Maybe this is the problem.

http://stackoverflow.com/questions/21289110/the-differences-between-gawk-and-mawk-column-width

Please install [GNU awk](http://ftp.gnu.org/gnu/gawk/) (gawk) and symblink gawk to awk or change the script.

http://askubuntu.com/questions/561621/choosing-awk-version-on-ubuntu-14-04

**Comment by receptor** [comment]
Absolutely right. Runs fine with GNU Awk 4.1.1, API: 1.1 (GNU MPFR 3.1.2-p3, GNU MP 6.0.0)
On Raspbian Jessie, update-alternatives says there is only mawk option, so I had to apt-get install gawk.
Thanks!
