### ISSUE TITLE
Not sure how important this

### ISSUE THREAD

**Issue by ateepy** [tbds/FreeContributor#5]
Not sure if I'm missing these domains now but i executed the example for unbound and got this:

used this: ./FreeContributor.sh -f dnsmasq -t NXDOMAIN

	 :: Downloading from URL: https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist

	 :: Downloading from URL: http://adblock.gjtech.net/?format=unix-hosts

	 Extracting domains from previous lists ...

	 Domains extracted using dnsmasq format: 81311    <<<is this bad?
dnsmasq: unrecognized service

    FreeContributor successfully installed
    Enjoy surfing in the web

    More info at https://tbds.github.io/FreeContributor/

**Comment by tbds** [comment]
You select dnsmsaq. For unbound is

    ./FreeContributor.sh -f unbound -t NXDOMAIN

>  Domains extracted using dnsmasq format: 81311    <<<is this bad?

No. This is just additional information. You just create a file with 81311 rules.

> dnsmasq: unrecognized service

You need to install a DNS resolver. In this case you select dnsmasq. 

Thank you, it's a bug, FreeContributor should have installed dnsmasq.

Which init system have you? Read [Install notes](https://github.com/tbds/FreeContributor/blob/master/INSTALL.md)

If systemd run as root the following command

    sudo systemctl enable dnsmasq && systemctl start dnsmasq

Note to use **only one** dns resolver. Exameple - to check if unbound is running 

If systemd run

    systemctl status unbound

If it show a message like

    Failed to dump process list, ignoring: Unit unbound.service not found.

Unbound is not running.

**Comment by ateepy** [comment]
oh wow, sorry i was so tired last night.
